In [1]:
# Importing the libraries
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing

import sklearn.metrics as metrics
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics.pairwise import pairwise_distances
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

from surprise.model_selection import cross_validate
from surprise.model_selection import train_test_split

from collections import defaultdict
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise import Reader

In [2]:
#Reading CSV files
data1 = pd.read_csv('phone_user_review_file_1.csv', encoding=('iso-8859-1'), low_memory= False)
data2 = pd.read_csv('phone_user_review_file_2 (1).csv', encoding=('iso-8859-1'), low_memory= False)
data3 = pd.read_csv('phone_user_review_file_3 (1).csv', encoding=('iso-8859-1'), low_memory= False)
data4 = pd.read_csv('phone_user_review_file_4 (1).csv', encoding=('iso-8859-1'), low_memory= False)
data5 = pd.read_csv('phone_user_review_file_5 (1).csv', encoding=('iso-8859-1'), low_memory= False)
data6 = pd.read_csv('phone_user_review_file_6 (1).csv', encoding=('iso-8859-1'), low_memory= False)

In [3]:
data1.head().T

,0,1,2,3,4
phone_url,/cellphones/samsung-galaxy-s8/,/cellphones/samsung-galaxy-s8/,/cellphones/samsung-galaxy-s8/,/cellphones/samsung-galaxy-s8/,/cellphones/samsung-galaxy-s8/
date,5/2/2017,4/28/2017,5/4/2017,5/2/2017,5/11/2017
lang,en,en,en,en,en
country,us,us,us,us,us
source,Verizon Wireless,Phone Arena,Amazon,Samsung,Verizon Wireless
domain,verizonwireless.com,phonearena.com,amazon.com,samsung.com,verizonwireless.com
score,10.0,10.0,6.0,9.2,4.0
score_max,10.0,10.0,10.0,10.0,10.0
extract,As a diehard Samsung fan who has had every Sam...,Love the phone. the phone is sleek and smooth ...,Adequate feel. Nice heft. Processor's still sl...,Never disappointed. One of the reasons I've be...,I've now found that i'm in a group of people t...
author,CarolAnn35,james0923,R. Craig,Buster2020,S Ate Mine
product,Samsung Galaxy S8,Samsung Galaxy S8,"Samsung Galaxy S8 (64GB) G950U 5.8"" 4G LTE Unl...",Samsung Galaxy S8 64GB (AT&T),Samsung Galaxy S8

In [4]:
data1.shape

(374910, 11)

In [5]:
#merging all data into one dataframe
data = pd.concat([data1,data2,data3,data4,data5,data6], ignore_index=True)

In [6]:
data.head()

,phone_url,date,lang,country,source,domain,score,score_max,extract,author,product
0,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Verizon Wireless,verizonwireless.com,10.0,10.0,As a diehard Samsung fan who has had every Sam...,CarolAnn35,Samsung Galaxy S8
1,/cellphones/samsung-galaxy-s8/,4/28/2017,en,us,Phone Arena,phonearena.com,10.0,10.0,Love the phone. the phone is sleek and smooth ...,james0923,Samsung Galaxy S8
2,/cellphones/samsung-galaxy-s8/,5/4/2017,en,us,Amazon,amazon.com,6.0,10.0,Adequate feel. Nice heft. Processor's still sl...,R. Craig,"Samsung Galaxy S8 (64GB) G950U 5.8"" 4G LTE Unl..."
3,/cellphones/samsung-galaxy-s8/,5/2/2017,en,us,Samsung,samsung.com,9.2,10.0,Never disappointed. One of the reasons I've be...,Buster2020,Samsung Galaxy S8 64GB (AT&T)
4,/cellphones/samsung-galaxy-s8/,5/11/2017,en,us,Verizon Wireless,verizonwireless.com,4.0,10.0,I've now found that i'm in a group of people t...,S Ate Mine,Samsung Galaxy S8

In [7]:
#Check a few observations and shape of the data-frame
data.shape

(1415133, 11)

In [8]:
data.describe()

              score  score_max
count  1.351644e+06  1351644.0
mean   8.007060e+00       10.0
std    2.616121e+00        0.0
min    2.000000e-01       10.0
25%    7.200000e+00       10.0
50%    9.200000e+00       10.0
75%    1.000000e+01       10.0
max    1.000000e+01       10.0

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1415133 entries, 0 to 1415132
Data columns (total 11 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   phone_url  1415133 non-null  object
 1   date       1415133 non-null  object
 2   lang       1415133 non-null  object
 3   country    1415133 non-null  object
 4   source     1415133 non-null  object
 5   domain     1415133 non-null  object
 6   score      1351644 non-null  float64
 7   score_max  1351644 non-null  float64
 8   extract    1395772 non-null  object
 9   author     1351931 non-null  object
 10  product    1415132 non-null  object
dtypes: float64(2), object(9)
memory usage: 118.8+ MB

In [10]:
#check for missing values
data.isnull().values.any()

True

In [11]:
null_counts = data.isnull().sum()
print (null_counts)

phone_url        0
date             0
lang             0
country          0
source           0
domain           0
score        63489
score_max    63489
extract      19361
author       63202
product          1
dtype: int64

In [12]:
data_copy = data.copy()

In [13]:
#  Impute the missing values if there is any and filling the null values in column 'score' and 'score_max' 
data = data.fillna(data.median())

In [14]:
data = data.dropna() # dropping the null values

In [15]:
# Round oﬀ scores to the nearest integers 
data['score'] = data['score'].astype(int) 
data['score_max'] = data['score_max'].astype(int)

In [16]:
data.shape

(1336416, 11)

In [17]:
#checking duplicates if any and drop duplicates
data_d = data.drop_duplicates()

In [18]:
# Drop irrelevant features. Keep features like Author, Product, and Score
data_d.drop(['phone_url','date','lang','country','source','domain','score_max','extract'], axis = 1, inplace = True)

In [19]:
data_df = data_d.copy()

In [20]:
data_d.shape

(1331600, 3)

In [21]:
# Keeping only 1000000 data samples, random state=612
df = data_d.sample(n=1000000, random_state=612)

In [22]:
data_d.shape

(1331600, 3)

In [23]:
# Identify the most rated features.
#sorting on products that got highest mean score
df.groupby('product')['score'].mean().sort_values(ascending=False).head()

product
Smartphone Sony Xperia E1 Desbloqueado Vivo Android 4.3 Tela 4 4GB 3G Wi-Fi CÃ¢mera 3MP - Branco                     10.0
Samsung Smartphone Samsung Galaxy S5 Desbloqueado Branco Android 4.4.2 4G CÃ¢mera 16 MP MemÃ³ria Interna 16 GB       10.0
Samsung Smartphone Samsung Galaxy S5 Duos Desbloqueado/ Dual Chip / Branco / 4G / 16 MP / Android 4.4                10.0
Samsung Smartphone Samsung Galaxy S5 Desbloqueado/ Branco / 4G / 16 MP / Android 4.4.2 / 16 GB / USB 3.0             10.0
Samsung Smartphone Samsung Galaxy S5 Desbloqueado Vivo Preto Android 4.4.2 4G CÃ¢mera 16 MP MemÃ³ria Interna 16GB    10.0
Name: score, dtype: float64

In [24]:
# Identify the users with most number of reviews. 
(df['author'].value_counts()).head()

Amazon Customer    57765
Cliente Amazon     14564
e-bit               6309
Client d'Amazon     5720
Amazon Kunde        3624
Name: author, dtype: int64

In [25]:
# The product that got most number of reviews.
df['product'].value_counts().head()

Lenovo Vibe K4 Note (White,16GB)     3908
Lenovo Vibe K4 Note (Black, 16GB)    3234
OnePlus 3 (Graphite, 64 GB)          3128
OnePlus 3 (Soft Gold, 64 GB)         2643
Huawei P8lite zwart / 16 GB          1994
Name: product, dtype: int64

In [26]:
# extracting authors who gave greater than 50 ratings
df1 = pd.DataFrame(columns=['author', 'count'])
df1['author']=df['author'].value_counts().index.tolist() 
df1['a_count'] = list(df['author'].value_counts() > 50)

In [27]:
# get names of indexes for which count column value is False
index_names = df1[ df1['a_count'] == False ].index

In [28]:
# drop these row indexes from dataFrame 
df1.drop(index_names, inplace = True) 
df1

              author count  a_count
0    Amazon Customer   NaN     True
1     Cliente Amazon   NaN     True
2              e-bit   NaN     True
3    Client d'Amazon   NaN     True
4       Amazon Kunde   NaN     True
..               ...   ...      ...
674           Ganesh   NaN     True
675             Ralf   NaN     True
676             Jens   NaN     True
677            Roger   NaN     True
678          Dominik   NaN     True

[679 rows x 3 columns]

In [29]:
# extracting product that got more than 50 ratings
df2 = pd.DataFrame(columns=['product', 'p_count'])
df2['product']=df['product'].value_counts().index.tolist() 
df2['p_count'] = list(df['product'].value_counts() > 50)

In [30]:
# get name_indexes for which count column value is False
index_names = df2[ df2['p_count'] == False ].index 
# drop these row indexes from dataFrame 
df2.drop(index_names, inplace = True)
df2

                                                product  p_count
0                      Lenovo Vibe K4 Note (White,16GB)     True
1                     Lenovo Vibe K4 Note (Black, 16GB)     True
2                           OnePlus 3 (Graphite, 64 GB)     True
3                          OnePlus 3 (Soft Gold, 64 GB)     True
4                           Huawei P8lite zwart / 16 GB     True
...                                                 ...      ...
4341  Sony Xperia go - Smartphone libre (pantalla tÃ...     True
4342  Sony Ericsson S500i mysterious green (black) H...     True
4343  LG Electronics L70 Smartphone (11,4 cm (4,5 Zo...     True
4344  Nokia Lumia 530 Smartphone 3G (Ecran: 4 pouces...     True
4345  Samsung Galaxy S5 SM-G900H 16GB Factory Unlock...     True

[4346 rows x 2 columns]

In [31]:
# selecting data where product is having more than 50 ratings.  
df3 = df[df['product'].isin(df2['product'])] 
df3

,score,author,product
1005326,10,Paul B,Samsung i897 Captivate Android Smartphone Gala...
453603,10,Yuvraj,"Blu Win JR LTE (Grey, 4GB)"
498651,2,Joyce D. Pratt,"BLU Vivo XL Smartphone - 5.5"" 4G LTE - GSM Unl..."
1017703,10,David B,Samsung S3350 Chat 335 Sim Free Mobile Phone
936413,10,Sebastian,"Samsung E1190 Handy (3,6 cm (1,43 Zoll) Displa..."
...,...,...,...
577008,8,Javier,Huawei Ascend Y330 - Smartphone libre Android ...
771460,8,Patrix,"Huawei Ascend G510 Smartphone Touch, Fotocamer..."
600716,2,Amazon Customer,"Apple iPhone 5C Factory Unlocked Cellphone, 8G..."
838993,10,majere1975,"Samsung Smartphone Galaxy S Advance, Display 4..."
588916,10,ALBERT M. MASSILLON,BLU Dash JR K Smartphone - Unlocked - Black

In [32]:
df4 = df3[df3['author'].isin(df1['author'])]
df4

,score,author,product
936413,10,Sebastian,"Samsung E1190 Handy (3,6 cm (1,43 Zoll) Displa..."
290678,8,sara,"Samsung SM-N910F Galaxy Note 4 Smartphone, 32 ..."
476314,10,ÐÐ²Ð³ÐµÐ½Ð¸Ð¹,Sony Xperia Z1 Compact (Ð»Ð°Ð¹Ð¼)
223332,8,Amazon Customer,Motorola Moto G 3rd Generation SIM-Free Smartp...
361379,10,e-bit,Smartphone Motorola Moto G 4 Play XT1603
...,...,...,...
396020,2,Amazon customer,Tracfone Motorola Moto E Android Prepaid Phone...
1222820,8,Qantas,Sony Ericsson K810i Cyber-shot
1170633,9,Capyto,Samsung M150 Cep Telefonu
577008,8,Javier,Huawei Ascend Y330 - Smartphone libre Android ...
600716,2,Amazon Customer,"Apple iPhone 5C Factory Unlocked Cellphone, 8G..."

In [33]:
df4.shape

(108983, 3)

In [34]:
#build a popularity based model

In [36]:
#calculating the mean score for a product by grouping it.
ratings_mean_count = pd.DataFrame(df.groupby('product')['score'].mean())

In [37]:
# calculating the number of ratings a product got
ratings_mean_count['rating_counts'] = pd.DataFrame(df.groupby('product')['score'].count())

In [38]:
# recommend top 5 mobile phones
ratings_mean_count.sort_values(by=['score','rating_counts'], ascending=[False,False]).head()

                                                    score  rating_counts
product
Samsung Galaxy Note5                                 10.0            144
Nokia Smartphone Nokia Lumia 520 Desbloqueado O...   10.0            132
Motorola Smartphone Motorola Moto X Desbloquead...   10.0            131
Samsung Smartphone Galaxy Win Duos Branco Desbl...   10.0            127
Motorola Smartphone Motorola Moto G Dual Chip D...   10.0            126

In [39]:
data_pb = df
df

,score,author,product
1005326,10,Paul B,Samsung i897 Captivate Android Smartphone Gala...
453603,10,Yuvraj,"Blu Win JR LTE (Grey, 4GB)"
1010409,10,Pankaj Bhalla,"Lenovo P780 (Deep Black, 4GB)"
866960,6,Bgrazina,Samsung Galaxy XCover 2
498651,2,Joyce D. Pratt,"BLU Vivo XL Smartphone - 5.5"" 4G LTE - GSM Unl..."
...,...,...,...
873202,4,Dudls,Nokia 301 Dual
1267485,8,Cintaaa__,LG Viewty KU990
588916,10,ALBERT M. MASSILLON,BLU Dash JR K Smartphone - Unlocked - Black
102484,2,Amazon Customer,Samsung Galaxy S6 SM-G920F 32GB (FACTORY UNLOC...
382181,2,Amazon Customer,Sony Xperia Z3 D6653 16GB (FACTORY UNLOCKED) G...

In [40]:
df4.groupby('product')['score'].mean().head()

product
3220                                                                                                                                                                                                      10.000000
5.5-Inch Unlocked Lenovo A850 3G Smartphone-(960x540) Quad Core 4GB MT6582m 1331MHz Android 4.2 Dual Camera +Dual SIM -Black (Rooted + Google Play)                                                        4.500000
AICEK Coque ASUS ZenFone 2 ZE550ML/ZE551ML, AICEK Etui Silicone Gel ASUS ZenFone 2 Housse Antichoc ZenFone 2 Transparente Souple Coque de Protection pour ASUS ZenFone 2(5.5 Pouces)                       9.583333
AICEK Coque ASUS ZenFone 3 ZE520KL, AICEK Etui Silicone Gel ASUS ZenFone 3 Housse Antichoc ZenFone 3 Transparente Souple Coque de Protection pour ASUS ZenFone 3(5.2 Pouces)                               8.421053
AICEK Coque Samsung Galaxy A3 2016, AICEK Etui Silicone Gel Samsung Galaxy A3 2016 (A310F) Housse Antichoc Samsung A3 Transparente Souple Coque De Protection Pour Samsung Galaxy A3 2016 (4,7 pouces)     8.865672
Name: score, dtype: float64

In [41]:
df4.groupby('product')['score'].mean().sort_values(ascending=False).head()

product
3220                                                                    10.0
Samsung E1190 SIM free mobile phone                                     10.0
Samsung E1150i Klapphandy 3,6 cm (1,43 Zoll) Display titanium-silver    10.0
Samsung E1150i Klapphandy 3,6 cm (1,43 Zoll) Display ruby-red           10.0
Samsung E1150 Handy (extralange Akkulaufzeit) titanium-silver           10.0
Name: score, dtype: float64

In [42]:
df4.groupby('product')['score'].count().sort_values(ascending=False).head()

product
Lenovo Vibe K4 Note (White,16GB)       2334
Lenovo Vibe K4 Note (Black, 16GB)      1899
OnePlus 3 (Graphite, 64 GB)            1433
OnePlus 3 (Soft Gold, 64 GB)           1316
Lenovo Vibe K5 (Gold, VoLTE update)    1167
Name: score, dtype: int64

In [43]:
ratings_mean_count = pd.DataFrame(df4.groupby('product')['score'].mean())

In [45]:
ratings_mean_count['rating_counts'] = pd.DataFrame(df4.groupby('product')['score'].count())

In [46]:
ratings_mean_count.head()

                                                        score  rating_counts
product
3220                                                10.000000              1
5.5-Inch Unlocked Lenovo A850 3G Smartphone-(96...   4.500000              4
AICEK Coque ASUS ZenFone 2 ZE550ML/ZE551ML, AIC...   9.583333             24
AICEK Coque ASUS ZenFone 3 ZE520KL, AICEK Etui ...   8.421053             19
AICEK Coque Samsung Galaxy A3 2016, AICEK Etui ...   8.865672             67

#Build a collaborative filtering model using SVD.

In [47]:

# arranging columns in the order of user id,item id and rating to be fed in the svd
columns_titles = ['author','product','score']
df_data = data_df.reindex(columns=columns_titles)

In [48]:
# Keep only 5000 data samples. Use random state=612
sv_data = df_data.sample(n=5000, random_state=612)

In [49]:
# Read dataset.
reader = Reader(rating_scale=(1, 10))
data_U = Dataset.load_from_df(sv_data,reader = reader)

In [54]:
# Use user_based true/false to switch between user-based or item-based collaborative filtering
from surprise import KNNWithMeans
trainset, testset = train_test_split(data_U, test_size=.15)
algo = KNNWithMeans(k=5, sim_options={'name': 'pearson_baseline', 'user_based': True})
algo.fit(trainset)

Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.

In [55]:
# we can now query for specific predicions
uid = 'Frances DeSimone'  # raw user id
iid = 'Samsung Galaxy Star Pro DUOS S7262 Unlocked Ce.'  # raw item id

In [56]:
# get a prediction for specific users and items.
pred = algo.predict(uid, iid, verbose=True)

user: Frances DeSimone item: Samsung Galaxy Star Pro DUOS S7262 Unlocked Ce. r_ui = None   est = 8.00   {'was_impossible': True, 'reason': 'User and/or item is unknown.'}

In [57]:
# run the trained model against the testset
test_pred = algo.test(testset)

In [58]:
test_pred

[Prediction(uid='mikhet', iid='Sony Ericsson Xperia X10 Mini Pro', r_ui=5.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rajat', iid='Samsung Galaxy J7 SM-J700F (Black, 16GB)', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='ksinbln', iid='ALCATEL ONETOUCH 1010D-2AALDE1 One Touch Tiger Handy (3,7 cm (1,5 Zoll) Display, 4MB RAM, Dual-Band GSM, micro-USB) schwarz', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='Motorola Moto G 3rd Generation (Black, 8GB)', r_ui=8.0, est=10, details={'actual_k': 1, 'was_impossible': False}),
 Prediction(uid='Vincent', iid='Huawei P8lite zwart / 16 GB', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='ertanonkok', iid='BlackBerry Bold 9700 0.25GB Siyah', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Andy', iid='Huawei Mate 8 NXT-L29 32GB Dual SIM Factory Unlocked GSM Smartphone - International Version, No Warranty (Moonlight Silver)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='michelange', iid='Acer Liquid E3 Duo Smartphone dÃ©bloquÃ© 4,7 pouces 4 Go Double SIM Android Jelly Bean Noir', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='eduardo de luca', iid='Smartphone Nokia Lumia 630 Dual Sim Desbloqueado Branco', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Cliente Amazon', iid='Nokia Lumia 520 Smartphone, Black [Italia]', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='karandeepchopra', iid='Google Nexus 5', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Osmann', iid='Nokia 6710 Navigator titanium (GPS, A-GPS, UMTS, MP3, Kamera mit 5 MP, Ovi Karten) Handy', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Cindy', iid='Samsung Galaxy J1 Smartphone dÃ©bloquÃ© 3G (Ecran : 4,3 pouces - 4 Go - Simple Micro-SIM - Android 4.4 KitKat) Blanc', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Ravi', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='JK', iid='BlackBerry Classic Smartphone 3.5" 16GB - Factory Unlocked (White) - International Version No Warranty', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Christian Konrath', iid='Huawei Ascend G700 Smartphone (12,7 cm (5 Zoll) Touchscreen, 8 Megapixel Kamera, 8 GB Interner Speicher, Android 4.2) schwarz', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='fondaz', iid='Nokia Lumia 925 Smartphone dÃ©bloquÃ© 4G (Ecran: 4.5 pouces - 16 Go - Windows Phone 8) Blanc', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='jean jj', iid='Samsung E300 Galaxy S4 IV E300 S/K 32GB 13MP 5" 4G LTE i9505 Unlocked SmartPhone', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='GamerGirl315', iid='LG Optimus F6 4GB Android 4G LTE Smartphone - T-Mobile', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='JUAN A.', iid='Huawei Y550 - Smartphone libre Android (pantalla de 4.5", cÃ¡mara 5 Mp, 4 GB, Quad-Core 1.2 GHz, 1 GB de RAM), blanco', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Christian Deimer', iid='Huawei Ascend Y201 Pro Smartphone (8,9 cm (3,5 Zoll) Touchscreen, 3,2 Megapixel Kamera, 4 GB Interner Speicher, Android 4.0) schwarz', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Franklin L. Allbright', iid='LG Optimus G Pro E980 32GB Unlocked GSM 4G LTE Android Phone - Black', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Daniel Ferreira Alvarez', iid='Smartphone Motorola Novo Moto G DTV Colors, Dual Chip, 3G, 16GB - XT1069', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rianq', iid='Samsung SGH-C260 silber-weiss Handy', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='shnibz', iid='Motorola DROID RAZR M', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='franÃ§oise', iid='Nokia 108 TÃ©lÃ©phone portable Compact Dual SIM Noir', r_ui=4.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Klara', iid='Apple iPhone 3G', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='nas13190', iid='HTC HD2 Noir Windows Mobile 6.5 Professional', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Cliente Amazon', iid='Samsung Galaxy A5 2016 Smartphone LTE, 16GB, Nero', r_ui=8.0, est=7.25, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid='Ð\x92Ð»Ð°Ð´Ð¸Ð¼Ð¸Ñ\x80', iid='Apple iPhone 5s 16GB (Ñ\x81ÐµÑ\x80ÐµÐ±Ñ\x80Ð¸Ñ\x81Ñ\x82Ñ\x8bÐ¹)', r_ui=9.0, est=8.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid='petebakewell', iid='Motorola M3788', r_ui=4.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='MOTOROLABRR', iid='Sony Ericsson Xperia X10', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rohit Dhiman', iid='Lenovo Vibe K5 (Grey)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Olena', iid='LG G Flex 2 H959 5.5" 32GB - Factory Unlocked International - Red', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Oleg', iid='Microsoft Nokia Lumia 720 Smartphone (4,3 Zoll (10,9 cm) Touch-Display, 8 GB Speicher, Windows 8) cyan', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='Sony Xperia XZ - Unlocked Smartphone - 32GB - Forest Blue (US Warranty)', r_ui=10.0, est=6.866071428571429, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid='Oliveira', iid='Samsung GALAXY S4', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Mattia', iid='Sony Mobile Xperia M2 Smartphone, Bianco [Italia]', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='www.maxim.by', iid='Sony Xperia J ST26i', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Honor7lite ', iid='Huawei Honor 7 Lite Dual-SIM â\x80\x90Android-puhelin, harmaa', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='SophieK', iid='Hyperion EA Apple iPhone 4S 16GB 3G WiFi White Smartphone AT&T', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='e-bit', iid='Smartphone Motorola Moto G 5 XT1672', r_ui=8.0, est=10, details={'actual_k': 1, 'was_impossible': False}),
 Prediction(uid='Andrea Dodaro', iid="Huawei P9 Lite Smartphone, LTE, Display 5.2'' FHD, Processore Octa-Core Kirin 650, 16 GB Memoria Interna, 3GB RAM, Fotocamera 13 MP, Single-SIM, Android 6.0 Marshmallow, Bianco [Italia]", r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Eddy F.', iid='Huawei Nexus 6P unlocked smartphone, 32GB Gold (US Warranty)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Izzy', iid='HTC One X Unlocked Gsm Phone, 16GB, Gray', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Felix G.', iid='LG OPTIMUS G E975 32GB BLACK ANDROID FACTORY UNLOCKED LTE 4G 3G 2G (2G & 3G HSDPA 900/2100 & 4G LTE 800/900/1800/2100/2600 market dependent)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Damien', iid='Motorola - Moto E - Smartphone DÃ©bloquÃ© 4G (Ecran : 4,5 Pouces - 8 Go - Simple SIM - Android 6.0 Marshmallow) - Blanc', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Vale', iid='Samsung J710 Galaxy J7 Smartphone da 16 GB, Nero [Italia]', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='sunn', iid='Samsung Galaxy S6 (Black Sapphire, 32GB)', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Paul vdS', iid='Huawei P8 Lite wit / 16 GB', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='vituccio', iid='Sony Xperia S, Smartphone, Nero, Display 4.3 Pollici', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='UTKARSH MANE', iid='OnePlus 3 (Graphite, 64 GB)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='dereklee', iid='BlackBerry PRIV Factory Unlocked Smartphone, U.S. Warranty (Black)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Anna', iid='Microsoft Nokia 1110i light grey Handy', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='bo', iid='Sony Ericsson Xperia ray (Black)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='gilly64', iid='Nokia 8800', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='clelia', iid='Sony Ericsson Vivaz U5i', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='dominique', iid='LG Lotus', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid="Client d'Amazon", iid='Samsung Galaxy S5 mini Smartphone dÃ©bloquÃ© 4.5 pouces 16 Go Android Noir (import Allemagne)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Roberto', iid='Lenovo Motorola Moto G LTE Smartphone, Display 4.5", Fotocamera 5 MP, Memoria 8 GB, Quad-Core 1.2 GHz, 1 GB RAM, Micro SD, Android 4.4.3, Bianco [Italia]', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Sreekumar', iid='OnePlus 3 (Graphite, 64 GB)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Jens B.', iid='Huawei Ascend W1 Smartphone (10,2 cm (4 Zoll) Touchscreen, 5 Megapixel Kamera, 4 GB Interner Speicher, Win 8) blau', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='jeremie51qcr', iid='HP iPAQ 214 - De poche - Windows Mobile 6.0 - 4" couleur TFT ( 640 x 480 ) - Wi-Fi, Bluetooth', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=8.0, est=9.5, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid='Ratnakar Mahajan', iid='OnePlus 3T (Gunmetal, 6GB RAM + 64GB memory)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=9.5, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid='Sleepflowerics1987', iid='Samsung Galaxy S4 Mini', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Agata Miranda', iid="Cubot 2014 i piÃ¹ nuovi CUBOT S168 5.0 '' Android 4.4 Kitkat OS sbloccato Smartphone 3G - IPS TouchScreen MTK6582 Quad Core a 1,3 GHz 1 GB di RAM + 8GB ROM del telefono cellulare Dual SIM Dual Standby 5.0MP + 2.0MP doppia Cmaeras del cellulare di GPS di sostegno ", r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='diman3309', iid='Sony Ericsson K200i', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Lftpeace', iid='Samsung GT-E1182L E1182 DUOS Unlocked Quad-Band Dual SIM GSM Phone with Dual SIM Standby Support, FM Radio and Organizer - US Warranty - Silver', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='Lenovo Vibe K4 Note (Black, 16GB)', r_ui=10.0, est=9.2, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid='Jacob.t.kariampally', iid='Nokia Lumia 730 Dual SIM (Latest Model) - 8GB -DARK GREY (Unlocked) RM-1040', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rievaulx', iid='HTC Hero', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Polskiy', iid='LG KM500', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='trini castillo', iid='Huawei Honor 8 Unlocked Smartphone 32 GB Dual Camera - US Warranty (Sapphire Blue)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='kym sandford', iid='Pantech Break Out', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='matt', iid='LG ENV', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='pikacu', iid='Sony Ericsson XPERIA X10 Mini -Black Cep Telefonu', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='DELASIL', iid='Nokia E63', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='EmHa', iid='Sony Ericsson S500i', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='JuicyJ.', iid='Samsung GT-S5230 La Fleur', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Handy', iid='Samsung Galaxy J5 Smartphone (5 Zoll (12,7 cm) Touch-Display, 8 GB Speicher, Android 5.1) gold', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='srikanth', iid='Samsung Galaxy S3 i9300i Unlocked 16GB (Marble White)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rocco Mannetta', iid='Nokia 701 dark steel', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='debora', iid='Apple iPhone 3GS', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Mike Carroll', iid='LEAGOO EASYSMX Leagoo Lead 6 Smart Phone Android 4.4.2 MTK Dual-Core Processer 4.5 inch IPS Display 1600 mAh Lithium Battery Dual Camera 2G/3G Dual SIM Standby White', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='kash-ksu', iid='Nokia E51', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Ð¦Ð°Ñ\x80Ð¸ÐºÐµÐ²Ð¸Ñ\x87 Ð\x92Ð°Ñ\x81Ð¸Ð»Ð¸Ð¹', iid='Apple iPhone 5S 64Gb', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Caner', iid='LG Electronics G Flex 2 Smartphone (13,97 cm (5,5 Zoll) Full-HD-POLED-Display, Qualcomm Snapdragon 810 2-GHz-Octa-Core-Prozessor, 13-Megapixelkamera, 16 GB interner Speicher, Android 5.0) Platinum Silver', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='NILESH KUMAR', iid='Lenovo Vibe K4 Note (Black, 16GB)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Shri', iid='Samsung Galaxy J7 Prime', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='niranjannivash', iid='Apple iPhone 6s (Gold, 128GB)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Francesc Felipe Legaz', iid='Microsoft Lumia 640 XL Dual-SIM Smartphone (5,7 Zoll (14,5 cm) Touch-Display, 8 GB Speicher, Windows 8.1) orange', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Regina Ates', iid='Samsung Galaxy S III S3 T999 GSM Unlocked Android Smartphone - Marble White', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Zeal', iid='Nokia N81', r_ui=3.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Fabio Rosso', iid='CAT B15 Q Smartphone, Display 4 Pollici, Fotocamera 5 MP, Processore Quad-Core 1,3 GHz, Android 4.4 KitKat, Argento [Germania]', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='bragina_ok', iid='Blackberry Ð\x9cÐ¾Ð±Ð¸Ð»Ñ\x8cÐ½Ñ\x8bÐ¹ Ñ\x82ÐµÐ»ÐµÑ\x84Ð¾Ð½ Blackberry Q5', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),

In [59]:
# get RMSE
print("User-based Model : Test Set")
accuracy.rmse(test_pred, verbose=True)

User-based Model : Test Set
RMSE: 2.5506

2.550607094700349

In [62]:
reader = Reader(rating_scale=(1, 10))
data_I = Dataset.load_from_df(sv_data,reader = reader)
trainset2, testset2 = train_test_split(data_I, test_size=.15)

In [63]:
# Use user_based true/false to switch between user-based or item-based collaborative filtering
algo = KNNWithMeans(k=5, sim_options={'name': 'pearson_baseline', 'user_based': False})
algo.fit(trainset)

Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.

In [64]:
# run the trained model against the testset
test_pred = algo.test(testset)

In [65]:
test_pred

[Prediction(uid='mikhet', iid='Sony Ericsson Xperia X10 Mini Pro', r_ui=5.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rajat', iid='Samsung Galaxy J7 SM-J700F (Black, 16GB)', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='ksinbln', iid='ALCATEL ONETOUCH 1010D-2AALDE1 One Touch Tiger Handy (3,7 cm (1,5 Zoll) Display, 4MB RAM, Dual-Band GSM, micro-USB) schwarz', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='Motorola Moto G 3rd Generation (Black, 8GB)', r_ui=8.0, est=10, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid='Vincent', iid='Huawei P8lite zwart / 16 GB', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='ertanonkok', iid='BlackBerry Bold 9700 0.25GB Siyah', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Andy', iid='Huawei Mate 8 NXT-L29 32GB Dual SIM Factory Unlocked GSM Smartphone - International Version, No Warranty (Moonlight Silver)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='michelange', iid='Acer Liquid E3 Duo Smartphone dÃ©bloquÃ© 4,7 pouces 4 Go Double SIM Android Jelly Bean Noir', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='eduardo de luca', iid='Smartphone Nokia Lumia 630 Dual Sim Desbloqueado Branco', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Cliente Amazon', iid='Nokia Lumia 520 Smartphone, Black [Italia]', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='karandeepchopra', iid='Google Nexus 5', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Osmann', iid='Nokia 6710 Navigator titanium (GPS, A-GPS, UMTS, MP3, Kamera mit 5 MP, Ovi Karten) Handy', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Cindy', iid='Samsung Galaxy J1 Smartphone dÃ©bloquÃ© 3G (Ecran : 4,3 pouces - 4 Go - Simple Micro-SIM - Android 4.4 KitKat) Blanc', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Ravi', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='JK', iid='BlackBerry Classic Smartphone 3.5" 16GB - Factory Unlocked (White) - International Version No Warranty', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Christian Konrath', iid='Huawei Ascend G700 Smartphone (12,7 cm (5 Zoll) Touchscreen, 8 Megapixel Kamera, 8 GB Interner Speicher, Android 4.2) schwarz', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='fondaz', iid='Nokia Lumia 925 Smartphone dÃ©bloquÃ© 4G (Ecran: 4.5 pouces - 16 Go - Windows Phone 8) Blanc', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='jean jj', iid='Samsung E300 Galaxy S4 IV E300 S/K 32GB 13MP 5" 4G LTE i9505 Unlocked SmartPhone', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='GamerGirl315', iid='LG Optimus F6 4GB Android 4G LTE Smartphone - T-Mobile', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='JUAN A.', iid='Huawei Y550 - Smartphone libre Android (pantalla de 4.5", cÃ¡mara 5 Mp, 4 GB, Quad-Core 1.2 GHz, 1 GB de RAM), blanco', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Christian Deimer', iid='Huawei Ascend Y201 Pro Smartphone (8,9 cm (3,5 Zoll) Touchscreen, 3,2 Megapixel Kamera, 4 GB Interner Speicher, Android 4.0) schwarz', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Franklin L. Allbright', iid='LG Optimus G Pro E980 32GB Unlocked GSM 4G LTE Android Phone - Black', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Daniel Ferreira Alvarez', iid='Smartphone Motorola Novo Moto G DTV Colors, Dual Chip, 3G, 16GB - XT1069', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rianq', iid='Samsung SGH-C260 silber-weiss Handy', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='shnibz', iid='Motorola DROID RAZR M', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='franÃ§oise', iid='Nokia 108 TÃ©lÃ©phone portable Compact Dual SIM Noir', r_ui=4.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Klara', iid='Apple iPhone 3G', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='nas13190', iid='HTC HD2 Noir Windows Mobile 6.5 Professional', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Cliente Amazon', iid='Samsung Galaxy A5 2016 Smartphone LTE, 16GB, Nero', r_ui=8.0, est=2.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid='Ð\x92Ð»Ð°Ð´Ð¸Ð¼Ð¸Ñ\x80', iid='Apple iPhone 5s 16GB (Ñ\x81ÐµÑ\x80ÐµÐ±Ñ\x80Ð¸Ñ\x81Ñ\x82Ñ\x8bÐ¹)', r_ui=9.0, est=8.2, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid='petebakewell', iid='Motorola M3788', r_ui=4.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='MOTOROLABRR', iid='Sony Ericsson Xperia X10', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rohit Dhiman', iid='Lenovo Vibe K5 (Grey)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Olena', iid='LG G Flex 2 H959 5.5" 32GB - Factory Unlocked International - Red', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Oleg', iid='Microsoft Nokia Lumia 720 Smartphone (4,3 Zoll (10,9 cm) Touch-Display, 8 GB Speicher, Windows 8) cyan', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='Sony Xperia XZ - Unlocked Smartphone - 32GB - Forest Blue (US Warranty)', r_ui=10.0, est=10, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid='Oliveira', iid='Samsung GALAXY S4', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Mattia', iid='Sony Mobile Xperia M2 Smartphone, Bianco [Italia]', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='www.maxim.by', iid='Sony Xperia J ST26i', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Honor7lite ', iid='Huawei Honor 7 Lite Dual-SIM â\x80\x90Android-puhelin, harmaa', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='SophieK', iid='Hyperion EA Apple iPhone 4S 16GB 3G WiFi White Smartphone AT&T', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='e-bit', iid='Smartphone Motorola Moto G 5 XT1672', r_ui=8.0, est=10, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid='Andrea Dodaro', iid="Huawei P9 Lite Smartphone, LTE, Display 5.2'' FHD, Processore Octa-Core Kirin 650, 16 GB Memoria Interna, 3GB RAM, Fotocamera 13 MP, Single-SIM, Android 6.0 Marshmallow, Bianco [Italia]", r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Eddy F.', iid='Huawei Nexus 6P unlocked smartphone, 32GB Gold (US Warranty)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Izzy', iid='HTC One X Unlocked Gsm Phone, 16GB, Gray', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Felix G.', iid='LG OPTIMUS G E975 32GB BLACK ANDROID FACTORY UNLOCKED LTE 4G 3G 2G (2G & 3G HSDPA 900/2100 & 4G LTE 800/900/1800/2100/2600 market dependent)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Damien', iid='Motorola - Moto E - Smartphone DÃ©bloquÃ© 4G (Ecran : 4,5 Pouces - 8 Go - Simple SIM - Android 6.0 Marshmallow) - Blanc', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Vale', iid='Samsung J710 Galaxy J7 Smartphone da 16 GB, Nero [Italia]', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='sunn', iid='Samsung Galaxy S6 (Black Sapphire, 32GB)', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Paul vdS', iid='Huawei P8 Lite wit / 16 GB', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='vituccio', iid='Sony Xperia S, Smartphone, Nero, Display 4.3 Pollici', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='UTKARSH MANE', iid='OnePlus 3 (Graphite, 64 GB)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='dereklee', iid='BlackBerry PRIV Factory Unlocked Smartphone, U.S. Warranty (Black)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Anna', iid='Microsoft Nokia 1110i light grey Handy', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='bo', iid='Sony Ericsson Xperia ray (Black)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='gilly64', iid='Nokia 8800', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='clelia', iid='Sony Ericsson Vivaz U5i', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='dominique', iid='LG Lotus', r_ui=6.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid="Client d'Amazon", iid='Samsung Galaxy S5 mini Smartphone dÃ©bloquÃ© 4.5 pouces 16 Go Android Noir (import Allemagne)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Roberto', iid='Lenovo Motorola Moto G LTE Smartphone, Display 4.5", Fotocamera 5 MP, Memoria 8 GB, Quad-Core 1.2 GHz, 1 GB RAM, Micro SD, Android 4.4.3, Bianco [Italia]', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Sreekumar', iid='OnePlus 3 (Graphite, 64 GB)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Jens B.', iid='Huawei Ascend W1 Smartphone (10,2 cm (4 Zoll) Touchscreen, 5 Megapixel Kamera, 4 GB Interner Speicher, Win 8) blau', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='jeremie51qcr', iid='HP iPAQ 214 - De poche - Windows Mobile 6.0 - 4" couleur TFT ( 640 x 480 ) - Wi-Fi, Bluetooth', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=8.0, est=9.493406039029704, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid='Ratnakar Mahajan', iid='OnePlus 3T (Gunmetal, 6GB RAM + 64GB memory)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=9.493406039029704, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid='Sleepflowerics1987', iid='Samsung Galaxy S4 Mini', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Agata Miranda', iid="Cubot 2014 i piÃ¹ nuovi CUBOT S168 5.0 '' Android 4.4 Kitkat OS sbloccato Smartphone 3G - IPS TouchScreen MTK6582 Quad Core a 1,3 GHz 1 GB di RAM + 8GB ROM del telefono cellulare Dual SIM Dual Standby 5.0MP + 2.0MP doppia Cmaeras del cellulare di GPS di sostegno ", r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='diman3309', iid='Sony Ericsson K200i', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Lftpeace', iid='Samsung GT-E1182L E1182 DUOS Unlocked Quad-Band Dual SIM GSM Phone with Dual SIM Standby Support, FM Radio and Organizer - US Warranty - Silver', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Amazon Customer', iid='Lenovo Vibe K4 Note (Black, 16GB)', r_ui=10.0, est=9.2, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid='Jacob.t.kariampally', iid='Nokia Lumia 730 Dual SIM (Latest Model) - 8GB -DARK GREY (Unlocked) RM-1040', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rievaulx', iid='HTC Hero', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Polskiy', iid='LG KM500', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='trini castillo', iid='Huawei Honor 8 Unlocked Smartphone 32 GB Dual Camera - US Warranty (Sapphire Blue)', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='kym sandford', iid='Pantech Break Out', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='matt', iid='LG ENV', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='pikacu', iid='Sony Ericsson XPERIA X10 Mini -Black Cep Telefonu', r_ui=9.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='DELASIL', iid='Nokia E63', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='EmHa', iid='Sony Ericsson S500i', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='JuicyJ.', iid='Samsung GT-S5230 La Fleur', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Handy', iid='Samsung Galaxy J5 Smartphone (5 Zoll (12,7 cm) Touch-Display, 8 GB Speicher, Android 5.1) gold', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='srikanth', iid='Samsung Galaxy S3 i9300i Unlocked 16GB (Marble White)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Rocco Mannetta', iid='Nokia 701 dark steel', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='debora', iid='Apple iPhone 3GS', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Mike Carroll', iid='LEAGOO EASYSMX Leagoo Lead 6 Smart Phone Android 4.4.2 MTK Dual-Core Processer 4.5 inch IPS Display 1600 mAh Lithium Battery Dual Camera 2G/3G Dual SIM Standby White', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='kash-ksu', iid='Nokia E51', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Ð¦Ð°Ñ\x80Ð¸ÐºÐµÐ²Ð¸Ñ\x87 Ð\x92Ð°Ñ\x81Ð¸Ð»Ð¸Ð¹', iid='Apple iPhone 5S 64Gb', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Caner', iid='LG Electronics G Flex 2 Smartphone (13,97 cm (5,5 Zoll) Full-HD-POLED-Display, Qualcomm Snapdragon 810 2-GHz-Octa-Core-Prozessor, 13-Megapixelkamera, 16 GB interner Speicher, Android 5.0) Platinum Silver', r_ui=10.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='NILESH KUMAR', iid='Lenovo Vibe K4 Note (Black, 16GB)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Shri', iid='Samsung Galaxy J7 Prime', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='niranjannivash', iid='Apple iPhone 6s (Gold, 128GB)', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Francesc Felipe Legaz', iid='Microsoft Lumia 640 XL Dual-SIM Smartphone (5,7 Zoll (14,5 cm) Touch-Display, 8 GB Speicher, Windows 8.1) orange', r_ui=8.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Regina Ates', iid='Samsung Galaxy S III S3 T999 GSM Unlocked Android Smartphone - Marble White', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Zeal', iid='Nokia N81', r_ui=3.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Fabio Rosso', iid='CAT B15 Q Smartphone, Display 4 Pollici, Fotocamera 5 MP, Processore Quad-Core 1,3 GHz, Android 4.4 KitKat, Argento [Germania]', r_ui=2.0, est=8.002823529411765, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),

In [66]:
# get RMSE
print("Item-based Model : Test Set")
accuracy.rmse(test_pred, verbose=True)

Item-based Model : Test Set
RMSE: 2.5736

2.5736258142234063

In [67]:
#  Try cross validation techniques to get better results.
cross_validate(algo,data_U, measures=['RMSE'], cv=3, verbose=False)

Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.
Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.
Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.

{'test_rmse': array([2.60908946, 2.66919232, 2.63918779]),
 'fit_time': (0.6337075233459473, 0.4591193199157715, 0.6717054843902588),
 'test_time': (0.032320261001586914, 0.05779743194580078, 0.05498552322387695)}

##In what business scenario you should use popularity based Recommendation Systems ?
Ans- As the name suggests Popularity based recommendation system works with the trend or frequent used. It basically uses the items which are in trend right now. For example, if any product which is usually bought by every new user then there are chances that it may suggest that item to the user who just signed up.

The best example of this system is Google News

It is used by the travel companies selling holiday packages in a season, by Google News and other news websites to show Top Stories with images.

##In what business scenario you should use Collaborative Filtering based Recommendation Systems ?
Ans-Collaborative filtering systems make recommendations based on historic users’ preference for items (clicked, watched, purchased, liked, rated, etc.). The preference can be presented as a user-item matrix. 

Most websites like Amazon, YouTube, and Netflix use collaborative filtering as a part of their sophisticated recommendation system

##What other possible methods can you think of which can further improve the recommendation for diﬀerent users ?
Ans- Apart from Popularity and Collaborative Filtering , Content-based, Demographic, Utility based, Knowledge based and Hybrid recommendation system can be used as per the user needs.